### ISSUE TITLE
Fonts on the website

### ISSUE THREAD

**Issue by fontvu** [huda46/WebDocsPrj#1]
Hey,

I see that the fonts required on the website are bold Century and Lora. However, I am not sure what exactly are

- Important points?
- Headers and brand name?

Thanks, Phong.

**Comment by huda46** [comment]
Hey,

the business description was Noels part, as I know the Headers are the main titles and for the brand name, whenever you find the name BeFit in different paragraphs use lora. 
and Important points he means the offer that is presented in the home page.   
I hope that this helps, If you need anything else let us know.

huda

**Comment by fontvu** [comment]
But what about the rest in other pages? I.e. In ForProducts page, there are four paragraphs. What do we use in those?

**Comment by huda46** [comment]
you can use the  "Arial, Helvetica, sans-serif;"

I guess that we can use up to 3 different fonts in a webpage.

**Comment by leshinoe** [comment]
Hey sorry for late reply. Huda is right!
If any other questions arise, don't hesitate to contact.
Noel

**Comment by fontvu** [comment]
FYI @jaylin0114 @venttis-1
