### ISSUE TITLE
Suggestions for the contact and personal pages

### ISSUE THREAD

**Issue by jaylin0114** [huda46/WebDocsPrj#15]
Hi,

I would like to know if you can accept these changes:

1. The background of the registration and personal pages is set to your logo color. This is because they look pretty plain if it is white as in the wireframe.
2. The visual of the plan cards on the registration page is made with no borders around them to reduce too many square-like borders on the page.
<img width="1062" alt="Screen Shot 2023-01-08 at 22 41 30" src="https://user-images.githubusercontent.com/7136959/211221070-82b6ab67-100b-4f57-b870-240162d2fd22.png">
<img width="1054" alt="Screen Shot 2023-01-08 at 22 41 27" src="https://user-images.githubusercontent.com/7136959/211221072-628afa23-4349-4d17-8797-9ab7c6179340.png">

Please give me some feedback or other suggestions if you have any ideas or opinions on that.

**Comment by huda46** [comment]
hi, 

from my side I like it I have no problem. However, we also need Noel and Gregiś opinion.

**Comment by jaylin0114** [comment]
Hi,

I will keep the changes for now. If you have any suggestions for these, please feel free to raise an issue again.
Thanks.
