### ISSUE TITLE
Prototyp of pages : Befit, Privacy, Imprint and Terms of Services + Ostkreuz

### ISSUE THREAD

**Issue by venttis-1** [huda46/WebDocsPrj#6]
Hello, I am done with the pages of Befit, Privacy, Imprint and Terms of Services and I am looking forward for some feedback.

**Comment by fontvu** [comment]
FYI @GregiCami @huda46 @leshinoe , the website is online at https://huda46.github.io/WebDocsPrj/index.html

**Comment by leshinoe** [comment]
Thank you, so far so good! If we have any issues we will let you know!
